[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "pyadaptive"
author = "Tom Gustafsson"
home-page = "https://github.com/kinnala/pyadaptive"
requires=["numpy"]
classifiers = ["License :: OSI Approved :: MIT License"]

